#!/bin/bash

# dependencies /////////////////////////////////////////////////////////////////

ticker () {

	echo

	for ticker in '>  ' '>> ' '>>>'
	do
		echo -n -e "\r[  ${ticker}  ] ${1^}..."

		sleep 0.5
	done

	echo

	echo

}

if [[ $(id -u -n) = "root" ]]
then
	USER="${SUDO_USER:-root}"

	if [ "${USER}" = "root" ]
	then
		HOME=/root
	else
		HOME="/home/${USER}"
	fi
fi

ticker checking

package_managers_list=(
	"apt-get --quiet --quiet update > /dev/null 2>&1; apt-get --quiet --quiet install --yes"
	"dnf --quiet install --assumeyes"
	"yum --quiet install --assumeyes"
	"apk add --quiet"
	"pacman --sync --refresh --noconfirm --noprogressbar"
	"zypper --quiet --non-interactive install"
)

package="curl"

if [[ -z $(command -v "${package}") ]]
then
	for package_manager in "${package_managers_list[@]}"
	do
		entry="${package_manager%% *}"

		if [[ -n $(command -v "${entry}") ]]
		then
			eval "${package_manager} ${package} > /dev/null 2>&1"

			break
		fi
	done

	if [[ -z $(command -v "${package}") ]]
	then
		echo "[  !  ] Unable to install or binary not found /////////////////////// [ '${package}' ]"
		echo

		exit 1
	fi
fi

mkdir -p "${HOME}"/.local/bin

frobulator="${HOME}"/.local/bin/frobulator

version_online=$(curl -s -L get.frbltr.app | grep -m 1 '^# version=' | cut -d '"' -f 2)
version_local=$(grep -m 1 '^# version=' "${frobulator}" 2>/dev/null | cut -d '"' -f 2)

version_local="${version_local:-1970-01-01}"

if [ ! -f "${frobulator}" ] || [[ "${version_online}" > "${version_local}" ]]
then
	curl -s -L get.frbltr.app > "${frobulator}"

	chmod +x "${frobulator}"
fi

ticker initializing

source "${frobulator}"

# script ///////////////////////////////////////////////////////////////////////

script=$(basename -- "${BASH_SOURCE[0]}")

# version //////////////////////////////////////////////////////////////////////

version="2023-10-18"

# usage ///////////////////////////////////////////////////////////////////////

while (($#))
do
	case "${1}" in
		-directory)
			directory="${2}"

			shift
		;;

		-a|--all)
			option="all"
		;;

		-i|--industrial)
			option="exports"
		;;

		-g|--graphic)
			option="renders"
		;;

		-h|--help)
			echo
			echo -e "Usage: ./${script} [EXTENSION] | [OPTION] [PARAMETER]"
			echo
			echo -e "Utility options:"
			echo
			echo -e "-directory          Specify directory to load models from."
			echo
			echo -e "-a, --all           Full website framework and content update."
			echo
			echo -e "-i, --industrial    Models exports content update."
			echo -e "-g, --graphic       Models renders content update."
			echo
			echo -e "'${script}'         [ Version ${version} ]"
			echo

			exit
		;;

		"")
			# handle empty argument:
			# use default values specified in script

			:
		;;

		*)
			echo
			echo -e "Usage: ./${script} [EXTENSION] | [OPTION] [PARAMETER]"
			echo
			echo -e "${script}: Unknown option '${1}'"
			echo -e "Type './${script} --help' for help and usage information."
			echo

			exit 1

		;;

		esac

		shift
done

# clear ////////////////////////////////////////////////////////////////////////

frobulator.clear

# prompt ///////////////////////////////////////////////////////////////////////

frobulator.script "Setting up ${script#*-}"

# variables ////////////////////////////////////////////////////////////////////

# defaults /////////////////////////////////////////////////////////////////////

# functions ////////////////////////////////////////////////////////////////////

upload () {

	message="${1}"

	git add *

	git commit		\
		--all		\
		--message="$${message}"

	git push > /dev/null 2>&1

	echo
}

option () {

	for script in ${list[@]}
	do
		"${SHELL}" "${PWD}"/"${script}"
	done

	upload "Models update" &

	frobulator.fwd "Updating..."
	echo

	list=()
}

# requirements /////////////////////////////////////////////////////////////////

# update ///////////////////////////////////////////////////////////////////////

if [[ "${option}" = "directory" ]]
then
	export models_directory="${directory}"
fi

if [[ "${option}" = "all" ]]
then
	list+=(
		nathaneltitane-drawer
		nathaneltitane-industrial
		nathaneltitane-graphic
	)
fi

if [[ "${option}" = "drawer" ]]
then
	list+=(
		nathaneltitane-drawer
	)
fi

if [[ "${option}" = "industrial" ]]
then
	list+=(
		nathaneltitane-industrial
	)
fi

if [[ "${option}" = "graphic" ]]
then
	list+=(
		nathaneltitane-graphic
	)
fi

option ${list[@]}

list=()

frobulator.scs "Update" "[ Done ]"
echo
