#!/bin/bash

# dependencies /////////////////////////////////////////////////////////////////

if [[ -z $(command -v frobulator) ]]
then
	if [[ $(id -u -n) = "root" ]]
	then
		SUDO_HOME=/root

		USER="${SUDO_USER}"

		HOME=/home/"${USER}"
	fi

	if [[ -z $(command -v curl) ]]
	then
		yes | apt-get install curl
	fi

	if [ ! -d "${HOME}"/.local/bin ]
	then
		mkdir -p "${HOME}"/.local/bin
	fi

	curl -s -L get.frbltr.app > "${HOME}"/.local/bin/frobulator

	chmod +x "${HOME}"/.local/bin/frobulator
fi

. "${HOME}"/.local/bin/frobulator

# superuser ////////////////////////////////////////////////////////////////////

# script ///////////////////////////////////////////////////////////////////////

script=$(basename -- "${BASH_SOURCE[0]}")

# version //////////////////////////////////////////////////////////////////////

version="01-14-2023"

# usage ////////////////////////////////////////////////////////////////////////

# prompt ///////////////////////////////////////////////////////////////////////

frobulator.script "Setting up ${script#*-}"
echo

# variables ////////////////////////////////////////////////////////////////////

# defaults /////////////////////////////////////////////////////////////////////

# functions ////////////////////////////////////////////////////////////////////

frobulator.inf "Generating graphic content entries"
echo

frobulator.fwd "Writing..."
echo

# generate header

cat << 'INDEX-HEADER' -> "graphic/index.html"
		<script>

			$(function(){

				$.get("/modules/anchors.html", function (data) {

					$("#anchors").append(data);

				});

				}
			);

		</script>

		<!-- BEGIN INDEX -->

INDEX-HEADER

# values

extensions_list=(
	svg
)

for extension in ${extensions_list[@]}
do
	count=1

	for content_items in $(find graphic/ -type f -iname "*.${extension}")
	do
		IFS='/' read -r -a path <<< $(echo "${content_items}")

		# keep first container visible

		if [ "${count}" -eq 1 ]
		then
			container="container"
		else
			container="container hidden"
		fi

# generate content container

cat << CONTENT-CONTAINER ->> "graphic/index.html"
		<!-- BEGIN CONTAINER -->

		<div class='${container}'>

			<div class="flex flex-column">

				<div class='flex-cell flex-cell-center'>

					<img src="/${path[0]}/${path[1]}/${path[2]}"/>

				</div>

			</div>

		</div>

		<!-- END CONTAINER -->

CONTENT-CONTAINER

	((count++))

	done
done

# generate footer

cat << FOOTER ->> "graphic/index.html"
		<!-- END INDEX -->

		<div class="section" id="anchors">

		<div>

FOOTER

frobulator.inf "Entries" "[ ${count} ]"
echo

frobulator.scs "Graphic" "[ Done ]"
echo
