#!/bin/bash

# dependencies /////////////////////////////////////////////////////////////////

USER_HOME="${HOME}"

if [[ -z $(command -v frobulator) ]]
then
	if [[ $(id -u -n) = "root" ]]
	then
		if [ -z "${SUDO:-$HOME}" ]
		then
			SUDO_HOME=/root
		else
			SUDO_HOME="${SUDO:-$HOME}"
		fi

		USER="${SUDO_USER}"
		USER_HOME=/home/"${USER}"
	fi

	if [[ -z $(command -v curl) ]]
	then
		yes | apt-get install curl
	fi

	if [ ! -d "${USER_HOME}"/.local/bin ]
	then
		mkdir -p "${USER_HOME}"/.local/bin/frobulator
	fi

	curl -s -L get.frbltr.app > "${USER_HOME}"/.local/bin/frobulator

	chmod +x "${USER_HOME}"/.local/bin/frobulator
fi

. "${USER_HOME}"/.local/bin/frobulator

# superuser ////////////////////////////////////////////////////////////////////

# script ///////////////////////////////////////////////////////////////////////

script=$(basename -- "${BASH_SOURCE[0]}")

# version //////////////////////////////////////////////////////////////////////

version="10-20-2022"

# usage ////////////////////////////////////////////////////////////////////////

# prompt ///////////////////////////////////////////////////////////////////////

frobulator.script "Setting up ${script#*-}"
echo

# variables ////////////////////////////////////////////////////////////////////

stamp=$(date +"%m-%d-%Y")

# defaults /////////////////////////////////////////////////////////////////////

# functions ////////////////////////////////////////////////////////////////////

frobulator.inf "Generating model entries"
echo

frobulator.fwd "Writing..."
echo

# generate header

cat << MODEL-DRAWER-HEADER -> "modules/drawer.html"
<!-- scripts -->

<script src="/javascript/drawer.js" type="text/javascript"></script>

<script src="/javascript/year.js" type="text/javascript"></script>

<!-- drawer -->

<div class="drawer">

	<div class="drawer-button cursor-cell">

		<div class="icon icon-64 logo"></div>

	</div>

	<div class="drawer-container">

		<div class="grid grid-column">

			<!-- industrial -->

			<div class="section">

				<div class="grid-cell">

					<a class="button" data-link="/industrial/">

						<div class="grid grid-middle">

							<div class="grid-cell">

								<div class="logo-purple icon icon-flex"></div>

							</div>

							<div class="grid-cell">

								<div class="text-center">INDUSTRIAL DESIGN</div>

							</div>

						</div>

					</a>

				</div>

			</div>

			<!-- graphic -->

			<div class="section">

				<div class="grid-cell">

					<a class="button" data-link="/graphic/">

						<div class="grid grid-middle">

							<div class="grid-cell">

								<div class="logo-teal icon icon-flex"></div>

							</div>

							<div class="grid-cell">

								<div class="text-center">GRAPHIC DESIGN</div>

							</div>

						</div>

					</a>

				</div>

			</div>

			<!-- code -->

			<div class="section">

				<div class="grid-cell">

					<a class="button" href="https://github.com/nathaneltitane/" target="_blank">

						<div class="grid grid-middle">

							<div class="grid-cell">

								<div class="logo-black icon icon-flex"></div>

							</div>

							<div class="grid-cell">

								<div class="text-center">CODE</div>

							</div>

						</div>

					</a>

				</div>

			</div>

MODEL-DRAWER-HEADER



# generate footer

cat << MODEL-DRAWER-FOOTER ->> "modules/drawer.html"
		</div>

		<!-- copyright -->

		<div class="list section copyright">

			<div class="grid grid-column grid-middle">

				<div class="grid-cell text-center">

					Version // ${stamp}</br>
					Lego // Linux - Where Lego meets Linux</br>
					Nathanel Titane - ©  <text id="year"></text>

				</div>

			</div>

		</div>

	</div>

</div>

MODEL-DRAWER-FOOTER

frobulator.inf "Parsed model entries" "[ ${count} ]"
echo

frobulator.scs "Models drawer" "[ Done ]"
echo
