#!/bin/bash

# dependencies /////////////////////////////////////////////////////////////////

if [[ -z $(command -v frobulator) ]]
then
	if [[ $(id -u -n) = "root" ]]
	then
		SUDO_HOME=/root

		USER="${SUDO_USER}"

		HOME=/home/"${USER}"
	fi

	if [[ -z $(command -v curl) ]]
	then
		yes | apt-get install curl
	fi

	if [ ! -d "${HOME}"/.local/bin ]
	then
		mkdir -p "${HOME}"/.local/bin
	fi

	curl -s -L get.frbltr.app > "${HOME}"/.local/bin/frobulator

	chmod +x "${HOME}"/.local/bin/frobulator
fi

. "${HOME}"/.local/bin/frobulator

# superuser ////////////////////////////////////////////////////////////////////

# script ///////////////////////////////////////////////////////////////////////

script=$(basename -- "${BASH_SOURCE[0]}")

# version //////////////////////////////////////////////////////////////////////

version="01-14-2023"

# usage ////////////////////////////////////////////////////////////////////////

# prompt ///////////////////////////////////////////////////////////////////////

frobulator.script "Setting up ${script#*-}"
echo

# variables ////////////////////////////////////////////////////////////////////

stamp=$(date +"%m-%d-%Y")

# defaults /////////////////////////////////////////////////////////////////////

# functions ////////////////////////////////////////////////////////////////////

frobulator.inf "Generating content entries"
echo

frobulator.fwd "Writing..."
echo

# generate header

cat << MODEL-DRAWER-HEADER -> "modules/drawer.html"
<!-- scripts -->

<script src="/javascript/drawer.js" type="text/javascript"></script>

<script src="/javascript/load.js" type="text/javascript"></script>

<script src="/javascript/logo.js" type="text/javascript"></script>

<script src="/javascript/year.js" type="text/javascript"></script>

<!-- drawer -->

<div class="drawer">

	<div class="drawer-button cursor-cell">

		<div class="icon icon-64 logo"></div>

	</div>

	<div class="flex flex-column">

		<!-- industrial -->

		<div class="list section">

			<div class="flex-cell">

				<a class="button" data-link="/industrial/">

					<div class="flex flex-middle">

						<div class="flex-cell">

							<div class="logo-purple icon icon-flex"></div>

						</div>

						<div class="flex-cell">

							<div class="text-center">INDUSTRIAL DESIGN</div>

						</div>

					</div>

				</a>

			</div>

		</div>

		<!-- graphic -->

		<div class="list section">

			<div class="flex-cell">

				<a class="button" data-link="/graphic/">

					<div class="flex flex-middle">

						<div class="flex-cell">

							<div class="logo-teal icon icon-flex"></div>

						</div>

						<div class="flex-cell">

							<div class="text-center">GRAPHIC DESIGN</div>

						</div>

					</div>

				</a>

			</div>

		</div>

		<!-- code -->

		<div class="list section">

			<div class="flex-cell">

				<a class="button" href="https://github.com/nathaneltitane/" target="_blank">

					<div class="flex flex-middle">

						<div class="flex-cell">

							<div class="logo-black icon icon-flex"></div>

						</div>

						<div class="flex-cell">

							<div class="text-center">CODE</div>

						</div>

					</div>

				</a>

			</div>

		</div>

		<!-- copyright -->

		<div class="list section copyright">

			<div class="flex flex-column flex-center flex-middle">

				<div class="flex-cell">

					<div class="avatar avatar-64 avatar-center" href=""></div>

				</div>

			</div>

			<div class="flex-cell text-center">

				Version ${stamp}<br>

			</div>

			<div class="flex-cell section">

				<hr>

			</div>

			<div class="flex-cell text-center">

				Nathanel + Titane - Industrial Design<br>

			</div>

			<div class="flex-cell text-center">

				N Λ T H Λ N E L - ©  <text id="year"></text>

			</div>

		</div>

</div>
MODEL-DRAWER-HEADER

frobulator.inf "Entries" "[ ${count} ]"
echo

frobulator.scs "Drawer" "[ Done ]"
echo

